
java_test(
  name = "DotReaderTest",
  srcs = ["DotReaderTest.java"],
  test_class = "org.dubh.graphs.DotReaderTest",
  deps = [
    "//src/main/java/org/dubh/graphs",
    "@maven//:junit_junit"
  ]
)